{"timestamp":"2025-09-08T13:52:33.655230","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-08T13:52:33.655882","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/lignes_azure_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-08T13:52:33.730149Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T13:52:33.730401Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T13:52:33.730535Z","level":"info","event":"Current task name:trips_updates.to_duckdb_trips_updates","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T13:52:33.730616Z","level":"info","event":"Dag name:lignes_azure_ETL","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T13:52:33.780800","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"IOException","exc_value":"IO Error: Could not set lock on file \"/opt/airflow/data/duck.db\": Conflicting lock is held in /usr/local/bin/python3.12 (PID 4298). See also https://duckdb.org/docs/stable/connect/concurrency","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/lignes_azure_dag.py","lineno":38,"name":"duckdb_trip_updates_call"},{"filename":"/opt/airflow/dags/lignes_azure/gtfs_rt_trip_update.py","lineno":78,"name":"export_data_to_duckdb_tu"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-08T13:52:33.782324Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T13:52:33.782661Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T13:52:33.782778Z","level":"info","event":"Task:<Task(PythonOperator): trips_updates.to_duckdb_trips_updates>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-08T13:52:33.782866Z","level":"info","event":"Failure caused by IO Error: Could not set lock on file \"/opt/airflow/data/duck.db\": Conflicting lock is held in /usr/local/bin/python3.12 (PID 4298). See also https://duckdb.org/docs/stable/connect/concurrency","chan":"stdout","logger":"task"}
