{"timestamp":"2025-09-10T08:47:14.737290","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-10T08:47:14.739099","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/lignes_azure_dag.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-10T08:47:15.376333Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-10T08:47:15.376565Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-10T08:47:15.376750Z","level":"info","event":"Current task name:reseau_transport.download_reseau_transport","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-10T08:47:15.376856Z","level":"info","event":"Dag name:lignes_azure_ETL","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-10T08:49:29.806504","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"ConnectTimeout","exc_value":"HTTPSConnectionPool(host='chouette.enroute.mobi', port=443): Max retries exceeded with url: /api/v1/datas/OpendataRLA/gtfs.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7d9037172510>, 'Connection to chouette.enroute.mobi timed out. (connect timeout=None)'))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":920,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1215,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/lignes_azure_dag.py","lineno":33,"name":"download_reseau_transport_call"},{"filename":"/opt/airflow/dags/lignes_azure/gtfs_reseau_transport.py","lineno":14,"name":"download_data_rt"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":73,"name":"get"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py","lineno":59,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":589,"name":"request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py","lineno":703,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":665,"name":"send"}],"is_group":false,"exceptions":[]},{"exc_type":"MaxRetryError","exc_value":"HTTPSConnectionPool(host='chouette.enroute.mobi', port=443): Max retries exceeded with url: /api/v1/datas/OpendataRLA/gtfs.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7d9037172510>, 'Connection to chouette.enroute.mobi timed out. (connect timeout=None)'))","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py","lineno":644,"name":"send"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":841,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py","lineno":519,"name":"increment"}],"is_group":false,"exceptions":[]},{"exc_type":"ConnectTimeoutError","exc_value":"(<urllib3.connection.HTTPSConnection object at 0x7d9037172510>, 'Connection to chouette.enroute.mobi timed out. (connect timeout=None)')","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":787,"name":"urlopen"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":488,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":464,"name":"_make_request"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py","lineno":1093,"name":"_validate_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":753,"name":"connect"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":207,"name":"_new_conn"}],"is_group":false,"exceptions":[]},{"exc_type":"TimeoutError","exc_value":"[Errno 110] Connection timed out","exc_notes":[],"syntax_error":null,"is_cause":true,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py","lineno":198,"name":"_new_conn"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":85,"name":"create_connection"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py","lineno":73,"name":"create_connection"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-10T08:49:29.810377Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-10T08:49:29.810912Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-10T08:49:29.810994Z","level":"info","event":"Task:<Task(PythonOperator): reseau_transport.download_reseau_transport>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-10T08:49:29.811082Z","level":"info","event":"Failure caused by HTTPSConnectionPool(host='chouette.enroute.mobi', port=443): Max retries exceeded with url: /api/v1/datas/OpendataRLA/gtfs.zip (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7d9037172510>, 'Connection to chouette.enroute.mobi timed out. (connect timeout=None)'))","chan":"stdout","logger":"task"}
